In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder

In [2]:
x_test=pd.read_csv("test_loan.csv")
x_test.info()
x_test.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    object
 1   Gender             356 non-null    object
 2   Married            367 non-null    object
 3   Dependents         357 non-null    object
 4   Education          367 non-null    object
 5   Self_Employed      344 non-null    object
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB

(367, 12)

In [3]:
x_train=pd.read_csv("train_loan.csv")
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [4]:
x_train.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [5]:
x_test.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban

In [6]:
x_train=x_train.drop(['Loan_ID','Gender'],axis=1)
x_test=x_test.drop(['Loan_ID','Gender'],axis=1)

In [7]:
x_train.head()

,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [8]:
print(x_test['Married'].unique(),x_test['Education'].unique(),x_test['Self_Employed'].unique(),x_test['Property_Area'].unique())
print(x_train['Married'].unique(),x_train['Education'].unique(),x_train['Self_Employed'].unique(),x_train['Property_Area'].unique())
print(x_train.isna().sum())
print(x_train.shape,x_test.shape)
x_train=x_train.dropna()
x_test=x_test.dropna()
print(x_train.shape,x_test.shape)

['Yes' 'No'] ['Graduate' 'Not Graduate'] ['No' 'Yes' nan] ['Urban' 'Semiurban' 'Rural']
['No' 'Yes' nan] ['Graduate' 'Not Graduate'] ['No' 'Yes' nan] ['Urban' 'Rural' 'Semiurban']
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64
(614, 11) (367, 10)
(492, 11) (299, 10)

In [9]:
le_m=LabelEncoder()
x_train['Married']=le_m.fit_transform(x_train['Married'])
x_test['Married']=le_m.transform(x_test['Married'])
le_e=LabelEncoder()
x_train['Education']=le_e.fit_transform(x_train['Education'])
x_test['Education']=le_e.transform(x_test['Education'])
le_se=LabelEncoder()
x_train['Self_Employed']=le_se.fit_transform(x_train['Self_Employed'])
x_test['Self_Employed']=le_se.transform(x_test['Self_Employed'])
y_train=x_train['Loan_Status']
le_o=LabelEncoder()
y_train=le_o.fit_transform(y_train)
x_train=x_train.drop('Loan_Status',axis=1)
x_train.head()
y_train[:5]

array([0, 1, 1, 1, 1])

In [10]:
ohe=OneHotEncoder()
pa_train=ohe.fit_transform(x_train[['Property_Area']]).toarray()
pa_test=ohe.transform(x_test[['Property_Area']]).toarray()

In [13]:
x_train=x_train.drop('Property_Area',axis=1)
x_test=x_test.drop('Property_Area',axis=1)
x_train=pd.DataFrame(pa_train,columns=ohe.get_feature_names_out(['Property_Area']),index=x_train.index)
x_test=pd.DataFrame(pa_test,columns=ohe.get_feature_names_out(['Property_Area']),index=x_test.index)
train_df=pd.concat([x_train,pa_train],axis=1)

KeyError: "['Property_Area'] not found in axis"